language: node_js

node_js:
  - "node"
  - "lts/*"

# 缓存依赖
cache:
  directories:
    - node_modules


# 依赖安装
install:
  - npm install

# 构建脚本
script:
  - npm run  build 

# 分支白名单
branches:
  only:
    - master # 只对 master 分支进行构建
deploy:
  provider: releases
  api_key: $ENCRYPTED_GITHUB_TOKEN
  skip_cleanup: true
  on:
    tags: true